# Keycloak JWT validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/Digital-Wallet

# Eureka ? gateway uses lb:// so it needs eureka to resolve service names
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka

