spring.application.name=payment-service

server.port=8083

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Digital-Wallet

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Wallet Service URL
#Dps alterar para o nome de verdade por causa de eureka
#no localhost so adicionar http://before the service name
wallet.service.url=http://wallet-service

