# DB
spring.datasource.url=jdbc:postgresql://payment-db:5432/payment_db

# Keycloak JWT validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/Digital-Wallet

# Kafka ? producer (emits transaction events)
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Wallet Service ? use container name, not localhost
wallet.service.url=http://wallet-service:8082

# Eureka
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka