spring.application.name=user-service

# Server
server.port=8081

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=0000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security - OAuth2 Resource Server JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Digital-Wallet

# Keycloak Admin Client ? renamed to avoid Spring Boot namespace conflict
kc.server-url=http://localhost:8080
kc.realm=Digital-Wallet
kc.client-id=wallet-mobile-app
kc.client-secret=l3uaBooqytwhN72aHeNI9xBoDAnyPhhc

# Kafka Broker Address
spring.kafka.bootstrap-servers=localhost:9092

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Topic Name (custom property)
kafka.topic.name=user-creation-topic

# Eureka
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

